### ISSUE TITLE
Visio issues task2

### ISSUE THREAD

**Issue by arghyakusumdas** [arghyakusumdas/FourBytes#5]
1) Balance the level0 diagram. The level 0 digram SHOULD HAVE EXACTLY SAME ARROWS as your context diagram
e.g., the University Mangement in your level 0 diagram has 2 arrows called Research Project Data and course project data. But your context diagram does not have those arrows.

This is a very serious flaw in DFD. Please change it

2) Please draw all the diagrams in the same visio files instead of doing in two different files.

**Comment by squireco** [comment]
Context Diagram and Level-0 DFD files combined into one file and the arrow issue was resolved to all entity-process relations are represented accurately in both diagrams.
